#!/bin/bash
CPPNames='addtargets2 alignchime alignchimel alnparams alpha alpha2 fractid getparents globalalign2 make3way mx myutils path searchchime seqdb setnucmx sfasta tracebackbit uchime_main usort viterbifast writechhit'
ObjNames='addtargets2.o alignchime.o alignchimel.o alnparams.o alpha.o alpha2.o fractid.o getparents.o globalalign2.o make3way.o mx.o myutils.o path.o searchchime.o seqdb.o setnucmx.o sfasta.o tracebackbit.o uchime_main.o usort.o viterbifast.o writechhit.o'

rm -f *.o mk.stdout mk.stderr tmp.stderr

for CPPName in $CPPNames
do
  echo $CPPName >&2
  g++ $ENV_GCC_OPTS -c -D_FILE_OFFSET_BITS=64 -DNDEBUG=1 -DUCHIMES=1 $CPPName.cpp -o $CPPName.o  >> mk.stdout 2>> tmp.stderr
  cat tmp.stderr
	cat tmp.stderr >> mk.stderr
	rm -f tmp.stderr
done

LINK_OPTS=
#if [ `uname -s` == Linux ] ; then
#    LINK_OPTS=-static
#fi
g++ $LINK_OPTS $ENV_LINK_OPTS -g -o uchime $ObjNames >> mk.stdout 2>> tmp.stderr
cat tmp.stderr
cat tmp.stderr >> mk.stderr
rm -f tmp.stderr

#strip uchime
ls -lh uchime
sum uchime
